#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Need2Park.Resource", IsApplication=true)]

namespace Need2Park
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_parking_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int burger = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int esilehe_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int esileht_logoga = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int landing_backg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int loadingscreendot = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int map = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int map_tag = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int nool = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int SearchCursor = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int taust1_1024 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ylemine_logo = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int myButton = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ikoon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int MyActionBar = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Theme_MainTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
